sections:
  - name: heading
    index: 0
    title: "MVP PRD: Project Name"
    comments:
      - "[2024.04.20]"
  - name: overview
    index: 1
    title: "Overview"
    comments: 
      - "Maximum: 2 pages"
      - "What is this project about?"
      - "can we delete the comments"
      - "Describe succinctly and precisely its purpose."
      - "Include a 3-sentence (max) elevator pitch."
      -         ""WanderWise" is an innovative travel app designed to facilitate trip planning and exploration. At its core, the project aims to simplify the often stressful process of itinerary creation and discovery. Users can seamlessly access a wealth of curated itineraries crafted by fellow travelers, while also having the freedom to craft and share their own personalized routes.
        The purpose of WanderWise is to alleviate the hassle and uncertainty associated with planning trips by providing a platform where users can easily access and contribute to a diverse array of travel itineraries. Through intuitive features such as customizable routes, detailed tagging options (including price, time, and thematic tags), and the ability to toggle between public and private itineraries, WanderWise empowers users to tailor their travel experiences to their preferences and needs. The user can now navigate the app for different reasons, whether he wants to create an itinerary that he went through by selecting the starting and finishing point amongst intermediates points, or interactively save an itinerary that he is currently walking, but also as mentioned before he can pick an itinerary to discover, allowing you to have a social aspect to this app so that many users can interact by discovering new trips and by “liking” them.
        The app uses the Google Maps API for a smoother usage of an extensive existing platform while also allowing the user to sign in with his Google account. The app is free for use and was developed to target a wide age range of 18+ . Currently only available on Android with an offline functionality to still access your “liked” and created itineraries, our goal is to extend to IOS for a larger audience.
        In essence, WanderWise is your ultimate travel companion, offering a convenient and efficient solution for both novice and seasoned travelers alike. With WanderWise, embark on your next adventure with confidence, knowing that comprehensive trip planning is just a few taps away.
        "


  - name: history
    index: 2
    title: "History"
    comments: 
      - "Maximum 1 page"
      - "Describe the V1 POC as planned by Sprint10."
      - "What did you learn?"
      - "What is missing to bridge from PoC to MVP?"
      - "The idea for WanderWise emerged from recognizing that travel planning was often inefficient and stressful, discouraging people from exploring the world. This realization led to the development of a mobile app designed to simplify and enhance the process of creating and finding travel itineraries, while also building a community of travelers.
          Learning from the Prototype : 
          The development from concept to prototype provided valuable insights. The integration of the Google Maps API was crucial, enabling real-time navigation and customizable routes, which improved the user experience significantly. Additionally, user feedback confirmed the importance of social features like liking, saving, and sharing itineraries, highlighting the community aspect of the app.
          User tests showed that while users liked the intuitive design and easy itinerary customization, they wanted more advanced filtering options to quickly find itineraries based on specific criteria such as budget, duration, and themes.
          Bridging the Gap: From PoC to MVP
          To evolve from a proof of concept (PoC) to a minimum viable product (MVP), several improvements are necessary:
          Enhanced Personalization: Implementing machine learning to tailor itinerary suggestions based on users' past behaviors and preferences could greatly boost engagement.
          Cross-Platform Availability: Extending availability to iOS is critical to reach a wider audience and test the app’s effectiveness across different user groups.
          Scalability and Performance: It's vital to ensure the app can support a high volume of users and itineraries without performance issues, potentially requiring backend optimization and cloud solutions for scalability.
          Advanced Search and Filtering: More detailed search options are needed to allow users to efficiently find ideal itineraries. This could include filters for accessibility features, environmental impact, or user ratings.
          Marketing and Community Building: A strategic marketing campaign is crucial to attract initial users and build a thriving community. This should include digital marketing and collaboration with travel influencers to increase the app's visibility and credibility.
          By addressing these areas, WanderWise aims to progress from a functional PoC to an MVP that demonstrates its value and appeals to early adopters and potential investors.
          "

  - name: analysis
    index: 3
    title: "Analysis of the Situation"
    comments: 
      - "What are the competing products in the market today?"
      - "What are the complementary products in the market today?"
      - "As WanderWise prepares to carve out its niche in the travel industry, understanding the landscape of existing products is essential. This analysis will outline both the competing and complementary products currently available in the market, providing insights into potential challenges and opportunities for collaboration.
          Competing Products
          TripAdvisor: As a giant in the travel industry, TripAdvisor offers extensive user-generated content including reviews, recommendations, and itineraries. While not exclusively an itinerary planning tool, its vast database and community engagement present a formidable competition.
          Roadtrippers: Specializing in road trip planning, Roadtrippers allows users to plot routes and discover attractions, accommodations, and restaurants along the way. Its focus on road travel and rich content make it a direct competitor for users interested in driving itineraries.
          Google Trips (discontinued but relevant): Google Trips was an app that helped plan and organize travel by pulling information from user's emails and providing offline access to itinerary details. Its integration with other Google services posed a significant competitive edge.
          Komoot: Targeted at outdoor enthusiasts, Komoot offers detailed route planning for hiking and biking adventures. Its niche focus on outdoor activities competes with WanderWise’s potential offerings in similar domains.
          Complementary Products
          Booking.com and Airbnb: These platforms provide accommodation booking services which are essential once an itinerary is planned. Integration with such platforms could offer users a seamless experience from planning to booking.
          Yelp and Zomato: For dining options along an itinerary, Yelp and Zomato could complement WanderWise by providing reviews and suggestions for restaurants. Potential API integrations could enhance user experience by offering meal stops directly in the travel itinerary.
          Weather Apps: Real-time weather information is crucial for travelers. Integrating weather forecasts into WanderWise could improve the planning process, making it adaptive to environmental conditions.
          Culture Trip: With its focus on cultural content, Culture Trip can complement WanderWise by providing users with deep insights into the cultural aspects of their travel destinations, enhancing the overall richness of the travel planning process.
          Flight Booking Platforms (SkyScanner, Google Flights): These platforms could serve as essential complements to WanderWise, offering users the ability to book flights directly related to the itineraries they plan on the app.


          This analysis highlights that while there are strong competitors in the travel planning space, there are also numerous opportunities for WanderWise to integrate with or leverage complementary products to enhance its offerings. Developing partnerships or features that bridge these services could significantly boost WanderWise’s value proposition, making it not only a tool for itinerary planning but a comprehensive travel planning platform.

            "

  - name: value_proposition
    index: 4
    title: "The Value Proposition"
    comments: 
      - "Describe the value proposition and argue that it is:"
      - "1. Easy to communicate"
      - "2. Defensible"
      - "3. Relevant"

  - name: mvp
    index: 5
    title: "The MVP"
    subsections:
      - title: "Personas and Scenarios"
        comments: 
          - "Who are the target personas for this product?"
          - "Which is the key persona?"
          - "High-level scenarios to adopt, use and share the product."
      - title: "User Stories and Key Features"
        comments: 
          - "User stories about how various personas will use the product in context."
          - "Identify and prioritise the key features required."
          - "Justify the importance of each feature."
      - title: "Success Criteria"
        comments: 
          - "How will you evaluate the success of the MVP?"
          - "Metrics include user penetration, quality / satisfaction."
          - "If applicable, progress in discussions with ecosystem partners / investors / customers."
      - title: "Features Outside the Scope"
        comments: 
          - "The MVP must be viable and minimal."
          - "Which features don’t belong in it."
          - "How should these be eventually integrated and in what sequence."

  - name: non_functional_requirements
    index: 6
    title: "Non-Functional Requirements"
    subsections:
      - title: "Security, privacy, and data retention policies"
        comments: 
          - "Which are the applicable laws and regulations?"
          - "What are your internal policies?"
          - "Which privacy features do you need from the phone?"
      - title: "Adoptions, Scalability and Availability"
        comments:
          - "What kind of traffic patterns do you expect to see?"
          - "Are there known periods of bursty traffic that the MVP must be designed to support?"

  - name: functional_requirements
    index: 7
    title: "Functional Requirements"
    comments: 
      - "Max 3 pages."
      - "List the key features of the MVP precisely."
      - "Include appropriate architectural diagrams."
      - "Describe key internal functionality."

  - name: user_analytics
    index: 8
    title: "User Analytics and Acceptance"
    comments: 
      - "Goal: understand how users are using the app."
      - "Which are the key metrics?"
      - "What is the success criteria?"
      - "What is the analysis plan (link to data collection)?"
      - "Include relevant A/B testing ideas."

  - name: design
    index: 9
    title: "Design and Implementation"
    subsections:
      - title: "Frontend"
        comments: 
          - "List the key libraries, languages, components used by the MVP."
          - "If applicable, describe essential screens."
      - title: "Backend"
        comments: 
          - "Decompose the MVP into functional blocks."
      - title: "Data Model"
        comments: 
          - "What data are you collecting / managing?"
          - "How is it organised?"
          - "Where is it stored?"
          - "How is it shared/copied/cached?"
      - title: "Security Considerations"
      - title: "Infrastructure and Deployment"
        comments: 
          - "How is the application developed, tested and deployed?"
          - "Any special infrastructure requirements."
      - title: "Test Plan"
        comments: 
          - "How is the application developed, tested and deployed?"
          - "Any special infrastructure requirements."

  - name: timeline
    index: 10
    title: "Timeline/Resource Planning"
    comments: 
      - "What’s the overall schedule you’re working towards?"
      - "What resources are required?"
      - "What are the intermediate milestones?"
      - "List identified sprints"

  - name: monetization
    index: 11
    title: "Business Model"
    comments: 
      - "Expected operating Costs"
      - "Revenue Streams"

  - name: appendix
    index: 12
    title: "Appendix"
    comments: 
      - "This section is optional."
      - "Can include mockups, sequence diagrams, etc."
